sudo: required
services:
  - docker
before_install:
  - docker build -t skswami91/frontend-project -f Dockerfile.dev .
script:
  - docker run -e CI=true skswami91/frontend-nodejs npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react-frontend"
  env: "DockerReactFrontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-887637364220"
  bucket_path: "docker-react-frontend"
  access_key_id: "$AWS_ACESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master
