sudo: required
services:
  - docker
before_install:
  - docker build -t skswami91/frontend-project -f Dockerfile.dev .
script:
  - docker run -e CI=true skswami91/frontend-nodejs npm run test -- --coverage
